# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

#cmd_duration
format = """
$battery\
[î‚¶](#264653)\
$sudo\
$os\
$username\
[î‚°](bg:#2a9d8f fg:#264653)\
$directory\
[î‚°](fg:#2a9d8f bg:#e9c46a)\
$git_branch\
$git_status\
[î‚°](fg:#e9c46a bg:#f4a261)\
$python\
$conda\
[î‚°](fg:#f4a261 bg:#e76f51)\
$time\
[î‚´ ](fg:#e76f51)
$character
"""

# The blank line at the start of the prompt
add_newline=true
command_timeout=3000 #ms

[battery]
full_symbol = "ó°¹ "
charging_symbol = "ó°‚„ "
discharging_symbol = "ó°‚ƒ "
unknown_symbol = "ó°½ "
empty_symbol = "ó°‚ "
disabled = false
#style = "fg:#ff0000 bg:#ffffff"
format = "[î‚¶](#ff0000)[$symbol$percentage ](bg:#ff0000 fg:#ffffff)[î‚´ ](#ff0000)"


[[battery.display]]
threshold = 20
#style = "bg:#ff0000 fg:#ffffff"

[character]
format = "[â¯](bold #2a9d8f) "
success_symbol = "[â¯](bold green) "
error_symbol = "[â¯](bold red) "
#success_symbol = "[âœ](bold green)"
#error_symbol = "[âœ–](bold red)"

# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bold bg:#264653 fg:#ffffff"
#format = '[î¢: ]($style)'
format = '[ïŠ½ $user ]($style)'
disabled = false

#[sudo]
#style = "bg:#264653 fg:#ffffff"
#symbol = 'ğŸ‘©â€ğŸ’» '
#disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#264653"
disabled = true # Disabled by default

[os.symbols]
"Macos" = "îœ‘ "
Fedora = "ïŒŠ "

[directory]
style = "bold bg:#2a9d8f fg:#ffffff"
truncation_length = 4
truncate_to_repo = false
use_logical_path = true
format = "[ $path ]($style)[$read_only ]($style)"
repo_root_format = "[ $before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path ]($style)[ $read_only ]($style)"
disabled = false
read_only = "ğŸ”’"
truncation_symbol = "â€¦/"
home_symbol = "~"
use_os_path_sep = true

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
#"Code" = "î«© "
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
"Dropbox" = "ï…« "
"Videos" = "ó°¨œ "

# Keep in mind that the order matters. For example:
# "Important Documents" = " ó°ˆ™ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ó°ˆ™ " = " ó°ˆ™ï„ª "

[c]
symbol = "î˜ "
style = "bg:#f4a261 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[conda]
style = "bold bg:#f4a261 fg:#000000"
truncation_length = 1
format = "[$symbol$environment ]($style)"
symbol = "ğŸ…’ "
ignore_base = false
disabled = false

[docker_context]
symbol = "ïŒˆ "
#style = "bg:#06969A"
style = "bg:#f4a261 fg:#000000"
format = '[ $symbol $context ]($style)[ $path]($style)'
disabled = false
detect_extensions = []
detect_files = [
    "docker-compose.yml",
    "docker-compose.yaml",
    "Dockerfile",
]
detect_folders = []

[git_branch]
#symbol = "î‚ "
symbol = "î™"
style = "bold bg:#e9c46a fg:#000000"
format = '[ $symbol $branch ]($style)'
only_attached = false
always_show_remote = false
ignore_branches = []
disabled = false

[git_status]
style = "bold bg:#e9c46a fg:#000000"
format = '([\[$all_status$ahead_behind\]]($style))'
stashed = '\$'
ahead = "â‡¡"
behind = "â‡£"
up_to_date = ""
diverged = "â‡•"
conflicted = "="
deleted = "âœ˜"
renamed = "Â»"
modified = "!"
staged = "+"
untracked = "?"
typechanged = ""
ignore_submodules = false
disabled = false

[python]
pyenv_version_name = false
pyenv_prefix = "pyenv "
python_binary = [
    "python",
    "python3",
    "python2",
]
format = '[ via ${symbol}${pyenv_prefix}(${version} )]($style)'
version_format = "v${raw}"
style = "bold bg:#f4a261 fg:#000000"
symbol = "ó°Œ  "
disabled = false
detect_extensions = ["py"]
detect_files = [
    "requirements.txt",
    ".python-version",
    "pyproject.toml",
    "Pipfile",
    "tox.ini",
    "setup.py",
    "__init__.py",
]
detect_folders = []

[java]
symbol = "î‰– "
style = "bg:#f4a261 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#f4a261 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#f4a261 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨"
style = "bg:#f4a261 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%Y-%m-%d %H:%M"
#time_format = "%R"
style = "bold bg:#e76f51 fg:#ffffff"
format = '[ ïº $time ]($style)'

[cmd_duration]
min_time = 2000
format = "took [$duration]($style) "
style = "yellow bold"
show_milliseconds = false
disabled = true
show_notifications = false
min_time_to_notify = 45000
